/*
 * @Author: 李佳修
 * @Date: 2022-05-12 20:07:30
 * @LastEditTime: 2022-05-12 20:07:34
 * @LastEditors: 李佳修
 * @FilePath: /Share-Note/src/aws-exports.js
 */
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://qerwssnwgvhdddq7vpozveyilq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-n4cudg242jbevba2mske3gepky"
};


export default awsmobile;
